name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        gover: ['1.19', '1.20']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Install golang
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test and lint
      run: |
          go install gotest.tools/gotestsum@latest
          gotestsum --format testname -- -v -race -vet="" ./...
